apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bastos
  name: bastos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bastos
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bastos
    spec:
      containers:
        - image: nileshyadv/baston-eventos
          name: baston-eventos
          ports:
            - containerPort: 8089
          volumeMounts:
            - name: config-file
              mountPath: /config
      volumes:
        - name: config-file
          configMap:
            name: baston-eventos-config