apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: baston
  name: baston
spec:
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: baston
status:
  loadBalancer: {}